import BottomNav from "@/component/BottomNav";
import { navigationData } from "@/constant/nav";

import type { Metadata } from "next";

import style from "./page.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={style.layout_body}>
        {children}
        <BottomNav navigationData={navigationData} />
      </body>
    </html>
  );
}
